FORMAT: 1A

# CIG-Exchange Homepage API
This is a **API Blueprint** file that describes **CIG-Exchange Homapage API**.

# Group Contact Us

## invest/api/contact_us [/invest/api/contact_us]

### Contact Us [POST]
Send contact us email message.

+ Request (application/json)
    + Attributes (ContactUs Request)

+ Response 204

# Group Account

## invest/api/users/signup [/invest/api/users/signup]

### Signup [POST]
Create a new account.

+ Request (application/json)
    + Attributes (User Request)

+ Response 200 (application/json)
    + Attributes (User Response)

## invest/api/users/signin [/invest/api/users/signin]

### Signin [POST]
Login to existing account.
Either email or mobile should be specified.

+ Request (application/json)
    + Attributes (User Signin Request)

+ Response 200 (application/json)
    + Attributes (User Response)

## invest/api/users/send_otp [/invest/api/users/send_otp]

### Send OTP [POST]
Send one time password.
Supported types are "email" and "phone"

+ Request (application/json)
    + Attributes (OTP Send Request)

+ Response 204

## invest/api/users/verify_otp [/invest/api/users/verify_otp]

### Verify OTP [POST]
Verify one time password.
Supported types are "email" and "phone".
On success, jwt is returned.

+ Request (application/json)
    + Attributes (OTP Verify Request)

+ Response 200 (application/json)
    + Attributes (OTP Response)

## Data Structures

### ContactUs Request
+ name: name (string, required) - name
+ email: email (string, required) - email
+ message: message (string, required) - message

### User Request
+ name: First Name (string, required) - user first name
+ lastname: Last Name (string, required) - user last name
+ sex: male (string, required) - user sex
+ email: email@email.com (string, required) - user email
+ phone_code: +1 (string, required) - user mobile number code
+ phone_number: 1111111111 (string, required) - user mobile number

### User Signin Request
+ email: email@email.com (string) - user email
+ phone_code: +1 (string) - user mobile number code
+ phone_number: 1111111111 (string) - user mobile number

### User Response
+ uuid: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user account uuid

### OTP Send Request
+ uuid: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user account uuid
+ type: `email` (string, required) - otp type, supported values are 'email' and 'phone'

### OTP Verify Request
+ uuid: `fdb283d4-7341-4517-b501-371d22d27cfc` (string, required) - user account uuid
+ type: `email` (string, required) - otp type, supported values are 'email' and 'phone'
+ code: `123456` (string, required) - otp code

### OTP Response
+ jwt: `1234567890` (string, required) - jwt for futher auth

